import type { Lesson, Question, Term } from "./types";

export const terms: Term[] = [
  {
    id: "term-button",
    slug: "button",
    title: "按钮位 BTN",
    category: "牌桌位置",
    difficulty: "beginner",
    summary: "按钮位是每手牌最后行动优势最明显的位置。",
    content:
      "BTN 是 Button，也叫庄位或按钮位。德扑里按钮会每手顺时针移动。翻牌后，按钮位通常最后行动，所以能看到别人先怎么做，再决定下注、过牌或跟注，这是很大的信息优势。",
    examples: ["前面都弃牌时，BTN 可以用比前位更宽的范围开池。", "BTN vs BB 是最常见的单挑训练场景之一。"],
  },
  {
    id: "term-blinds",
    slug: "small-blind-big-blind",
    title: "小盲 / 大盲",
    category: "牌桌位置",
    difficulty: "beginner",
    summary: "每手牌开始前强制投入的两个盲注。",
    content:
      "按钮左边是小盲 SB，小盲左边是大盲 BB。盲注是强制投入，用来让底池一开始就有筹码。盲注位翻后通常位置不好，所以即使已经投入筹码，也不能什么牌都硬防守。",
    examples: ["盲注 10/20 表示小盲先放 10，大盲先放 20。", "BB 面对 BTN 开池时，因为已经投入大盲，防守范围会比其他位置宽。"],
  },
  {
    id: "term-position",
    slug: "position",
    title: "位置",
    category: "牌桌位置",
    difficulty: "beginner",
    summary: "你在一手牌中行动顺序的相对位置。",
    content:
      "位置决定你能不能后行动。后行动可以先看到对手选择，信息更多，错误更少。新手学习德扑时，位置比单手牌牌力更重要：同一手 KJo，在 BTN 可能能玩，在 UTG 通常就太松。",
    examples: ["BTN 是最好的位置。", "UTG 是前位，后面很多人没行动，所以范围要紧。"],
  },
  {
    id: "term-streets",
    slug: "streets",
    title: "翻前 / 翻牌 / 转牌 / 河牌",
    category: "基本规则",
    difficulty: "beginner",
    summary: "一手德扑分成四个主要决策阶段。",
    content:
      "翻前是只拿到两张手牌时的阶段；翻牌是发出三张公共牌；转牌是第四张公共牌；河牌是第五张公共牌。每个阶段都可能有下注、跟注、加注、弃牌或过牌。",
    examples: ["A♠K♠ 翻前很强，但翻牌没中也不一定能一直下注。", "河牌没有后续发牌，决策更接近最终摊牌。"],
  },
  {
    id: "term-community-cards",
    slug: "community-cards",
    title: "公共牌",
    category: "基本规则",
    difficulty: "beginner",
    summary: "桌面上所有玩家都能使用的牌。",
    content:
      "德州扑克每个玩家有两张私有手牌，桌面最多五张公共牌。最终从两张手牌和五张公共牌里选出最好的五张牌比大小。",
    examples: ["你拿 A♠K♠，桌面 A♥7♦2♣，你至少有一对 A。", "如果公共牌自己已经是顺子，所有还在牌局的人都能使用这副顺子。"],
  },
  {
    id: "term-pot",
    slug: "pot",
    title: "底池",
    category: "基本规则",
    difficulty: "beginner",
    summary: "所有玩家已经投入、等待争夺的筹码。",
    content:
      "底池是这手牌的奖金池。下注和跟注会让底池变大。很多决策都要看底池大小，比如底池赔率、下注尺度、bluff 需要成功的频率。",
    examples: ["底池 100，你下注 50，就是半池下注。", "对手下注越大，你跟注需要的胜率通常越高。"],
  },
  {
    id: "term-check-call-bet-raise-fold",
    slug: "actions",
    title: "过牌 / 下注 / 跟注 / 加注 / 弃牌",
    category: "基本动作",
    difficulty: "beginner",
    summary: "德扑里最常用的五类行动。",
    content:
      "过牌 check 是没人下注时选择不下注；下注 bet 是主动投入筹码；跟注 call 是补齐对手下注；加注 raise 是在对手下注基础上再提高价格；弃牌 fold 是放弃这手牌，不再争夺底池。",
    examples: ["没人下注时你不能 call，只能 check 或 bet。", "有人下注后，你可以 fold、call 或 raise。"],
  },
  {
    id: "term-showdown",
    slug: "showdown",
    title: "摊牌",
    category: "基本规则",
    difficulty: "beginner",
    summary: "河牌后仍有多人未弃牌时，比牌决定赢家。",
    content:
      "如果最后还有两个或更多玩家没有弃牌，就进入摊牌。系统会比较每个人最好的五张牌。也有很多手牌不摊牌就结束，因为其他人都弃牌了。",
    examples: ["你下注，所有人弃牌，你不用亮牌也能赢底池。", "河牌你跟注后双方摊牌，比谁的五张牌更大。"],
  },
  {
    id: "term-all-in",
    slug: "all-in",
    title: "All-in 全下",
    category: "基本动作",
    difficulty: "beginner",
    summary: "把自己剩余筹码全部投入这手牌。",
    content:
      "All-in 是把当前剩余筹码全部放进底池。全下后你不能再做更多行动，只等待后续发牌和结算。多人全下时可能出现边池，这会让结算更复杂。",
    examples: ["短码玩家翻前可能用强牌直接 all-in。", "多人筹码不同全下时，需要按每个人可争夺的金额分主池和边池。"],
  },
  {
    id: "term-gto",
    slug: "gto",
    title: "GTO",
    category: "核心概念",
    difficulty: "beginner",
    summary: "一种尽量不可被剥削的平衡策略。",
    content:
      "GTO 是 Game Theory Optimal。德扑里它不是每手牌都追求最大收益，而是让你的价值下注、诈唬、跟注和弃牌频率保持合理，降低对手针对你的空间。",
    examples: ["河牌用合适的价值牌和阻断牌组成下注范围。", "面对下注时按底池赔率保留足够防守频率。"],
  },
  {
    id: "term-mdf",
    slug: "minimum-defense-frequency",
    title: "MDF",
    category: "防守",
    difficulty: "intermediate",
    summary: "面对下注时，理论上至少需要继续防守的频率。",
    content:
      "MDF 用来避免对手任意下注都自动盈利。公式是 pot / (pot + bet)。它是一个框架，不是机械按钮，实际还要看范围、牌面、阻断牌和对手倾向。",
    examples: ["底池 100，对手下注 50，MDF = 100 / 150 = 66.7%。"],
  },
  {
    id: "term-exploit",
    slug: "exploit",
    title: "剥削策略",
    category: "实战调整",
    difficulty: "beginner",
    summary: "针对对手偏差主动偏离平衡策略。",
    content:
      "剥削策略的核心是找到对手频率偏差。如果对手过度弃牌，你可以提高诈唬频率；如果对手过度跟注，你应减少诈唬，扩大价值下注范围。",
    examples: ["对跟注站少 bluff，多薄价值。", "对翻牌 c-bet 后过度弃牌的人，提高 c-bet 频率。"],
  },
  {
    id: "term-blocker",
    slug: "blocker",
    title: "阻断牌",
    category: "牌面阅读",
    difficulty: "intermediate",
    summary: "你手里的牌减少了对手持有某些强牌或跟注牌的组合数。",
    content:
      "阻断牌可以帮助选择诈唬和 bluff-catch。比如你持有 A 黑桃，河牌同花完成时，对手拥有坚果同花的组合减少。",
    examples: ["拿着 A 高同花阻断牌时，更适合作为某些河牌 bluff 候选。"],
  },
  {
    id: "term-range",
    slug: "range",
    title: "范围",
    category: "核心概念",
    difficulty: "beginner",
    summary: "把对手可能持有的所有手牌组合放在一起思考。",
    content:
      "学习 GTO 时要从单手牌思维转向范围思维。你不是只问“我这手强不强”，而是问“我的整体范围在这个牌面上有什么优势，对手有哪些强牌、听牌和空气牌”。",
    examples: ["BTN 开池后在 A 高干燥面通常有范围优势。", "BB 防守范围有更多低张两对和暗三条组合。"],
  },
  {
    id: "term-ev",
    slug: "expected-value",
    title: "EV",
    category: "数学基础",
    difficulty: "beginner",
    summary: "一个决策长期平均能赚或亏多少。",
    content:
      "EV 是 Expected Value。短期结果会被运气影响，但学习策略时要评估长期期望值。一个河牌 bluff 即使这次失败，只要对手弃牌频率足够高，长期仍然可能是正 EV。",
    examples: ["底池 100，下注 50，纯 bluff 需要对手弃牌超过 33.3% 才立即盈利。"],
  },
  {
    id: "term-pot-odds",
    slug: "pot-odds",
    title: "底池赔率",
    category: "数学基础",
    difficulty: "beginner",
    summary: "用跟注成本和最终底池比较，判断需要多少胜率。",
    content:
      "底池赔率帮助你判断跟注是否合理。需要胜率 = 跟注金额 / 跟注后总底池。它不等于最终答案，因为还要考虑后续下注、隐含赔率和反向隐含赔率。",
    examples: ["底池 100，对手下注 50，你跟 50 赢 200，总共需要 25% 胜率。"],
  },
  {
    id: "term-equity",
    slug: "equity",
    title: "胜率 Equity",
    category: "数学基础",
    difficulty: "beginner",
    summary: "如果现在一路摊牌，你赢下底池的概率份额。",
    content:
      "Equity 是你的手牌或范围对另一个手牌或范围的胜率。听牌通常有不错 equity，但是否下注还要看 fold equity、位置、牌面和未来可实现程度。",
    examples: ["同花听牌到河牌大约有 35% 左右完成概率。"],
  },
  {
    id: "term-fold-equity",
    slug: "fold-equity",
    title: "弃牌收益",
    category: "进攻",
    difficulty: "intermediate",
    summary: "下注让对手弃牌带来的收益。",
    content:
      "Fold equity 是 bluff 和半诈唬的重要来源。你的牌就算暂时落后，只要下注能让对手弃掉足够多更好牌或高 equity 牌，下注就可能盈利。",
    examples: ["转牌用强听牌加注，既有成牌胜率，也能直接赢下底池。"],
  },
  {
    id: "term-cbet",
    slug: "continuation-bet",
    title: "C-bet",
    category: "翻后策略",
    difficulty: "beginner",
    summary: "翻前进攻者在翻牌继续下注。",
    content:
      "C-bet 的频率取决于范围优势、坚果优势、牌面湿度和位置。干燥 A 高面通常适合较高频率小注，连张同花湿润面则需要更谨慎。",
    examples: ["BTN vs BB，A72r 常见小注高频。", "987 两同花面对 BB 防守范围时要降低自动下注。"],
  },
  {
    id: "term-value-bet",
    slug: "value-bet",
    title: "价值下注",
    category: "进攻",
    difficulty: "beginner",
    summary: "希望被更差的牌跟注而下注。",
    content:
      "价值下注不是“我有强牌就下注”这么简单，而是判断对手会用哪些更差牌支付。对跟注过多的对手，可以扩大薄价值下注范围。",
    examples: ["对跟注站，顶对弱踢脚在一些河牌也可能薄价值下注。"],
  },
  {
    id: "term-bluff-catch",
    slug: "bluff-catch",
    title: "抓诈唬",
    category: "防守",
    difficulty: "intermediate",
    summary: "用只能赢诈唬、很难赢价值牌的牌跟注。",
    content:
      "Bluff-catch 的重点不是绝对牌力，而是对手价值牌和诈唬比例、下注尺度、你手里的阻断牌，以及对手是否真的有足够 bluff。",
    examples: ["河牌拿到阻断对手价值范围、且不阻断其诈唬范围的牌，更适合跟注。"],
  },
  {
    id: "term-nut-advantage",
    slug: "nut-advantage",
    title: "坚果优势",
    category: "范围分析",
    difficulty: "intermediate",
    summary: "某一方拥有更多最强牌组合。",
    content:
      "坚果优势会影响大注和超池下注。即使一方整体 equity 没有明显领先，只要拥有更多最强牌，也可能更适合使用大尺度施压。",
    examples: ["BB 在 764 这类低连张面可能有更多两对和顺子组合。"],
  },
  {
    id: "term-polarized-range",
    slug: "polarized-range",
    title: "两极化范围",
    category: "下注结构",
    difficulty: "intermediate",
    summary: "范围主要由强价值牌和诈唬组成，中等牌较少。",
    content:
      "大注通常更偏两极化：强牌想拿最大价值，弱牌靠弃牌收益盈利；中等摊牌价值通常更倾向过牌或小注。",
    examples: ["河牌大注往往代表强价值或 bluff，不太应该混入大量中等牌。"],
  },
];

export const lessons: Lesson[] = [
  {
    id: "lesson-gto-vs-exploit",
    slug: "gto-vs-exploit",
    title: "GTO 和剥削不是对立面",
    category: "学习路径",
    difficulty: "beginner",
    content:
      "GTO 给你一个不容易被打穿的基准线，剥削策略让你在发现对手偏差时获得额外收益。初学阶段应先学会范围、位置、底池赔率和基础频率，再学习如何偏离。",
    takeaways: ["先有基准，再谈偏离。", "没有读牌依据时，接近均衡。", "发现稳定偏差时，果断剥削。"],
  },
  {
    id: "lesson-player-types",
    slug: "player-types",
    title: "常见对手类型",
    category: "剥削策略",
    difficulty: "beginner",
    content:
      "德扑学习里最常见的剥削入口是对手类型。弃牌太多的人怕压力，跟注太多的人不信你，下注太少的人通常偏被动，过度激进的人会让范围失衡。",
    takeaways: ["对弃牌多的人多施压。", "对跟注多的人减少纯诈唬。", "对被动玩家的突然大注保持尊重。"],
  },
  {
    id: "lesson-preflop-position",
    slug: "preflop-position",
    title: "位置决定范围宽度",
    category: "翻前",
    difficulty: "beginner",
    content:
      "越靠后的位置，后面未行动玩家越少，能用更宽的范围开池。前位需要更紧，因为后面还有很多玩家可能拿到强牌或拥有位置优势。",
    takeaways: ["BTN 范围最宽。", "UTG 范围最紧。", "盲注位翻后经常没有位置，要谨慎防守。"],
  },
  {
    id: "lesson-range-first",
    slug: "range-first-thinking",
    title: "从单手牌转向范围",
    category: "GTO 基础",
    difficulty: "beginner",
    content:
      "GTO 学习的第一步是停止只看自己的两张牌。你需要估计自己和对手的范围，判断谁有范围优势、谁有坚果优势、哪些牌适合下注、哪些牌适合过牌保护整体范围。",
    takeaways: ["先问范围，再问单手牌。", "范围优势适合高频小注。", "坚果优势支持更大下注尺度。"],
  },
  {
    id: "lesson-bet-sizing",
    slug: "bet-sizing-basics",
    title: "下注尺度的基本逻辑",
    category: "GTO 基础",
    difficulty: "intermediate",
    content:
      "小注通常用于范围优势明显、想用大量牌施压的牌面；大注通常用于两极化范围，强牌拿价值，诈唬牌制造弃牌收益。不要把所有牌都用同一个尺度处理。",
    takeaways: ["小注偏高频和范围压力。", "大注偏两极化。", "中等牌不适合无脑打大。"],
  },
  {
    id: "lesson-defense-frequency",
    slug: "defense-frequency",
    title: "防守频率和 MDF",
    category: "GTO 防守",
    difficulty: "intermediate",
    content:
      "MDF 给你一个防守下限，避免对手任意 bluff 都赚钱。但实战不是机械按公式跟注：范围劣势、阻断牌差、对手诈唬不足时，可以低于 MDF；对手过度 bluff 时，可以高于 MDF。",
    takeaways: ["MDF 是框架，不是按钮。", "优先保留有 equity 和好阻断的牌。", "对手诈唬不足时少抓。"],
  },
  {
    id: "lesson-exploit-map",
    slug: "exploit-map",
    title: "常见漏洞和调整地图",
    category: "剥削策略",
    difficulty: "beginner",
    content:
      "剥削策略要把对手漏洞翻译成你的行动。弃牌太多就提高 bluff 和小注频率；跟注太多就减少 bluff，扩大价值；下注太少就多偷底池；加注太少就更放心薄价值。",
    takeaways: ["对过度弃牌者多 bluff。", "对跟注站多价值少诈唬。", "对被动玩家的大注少逞强。"],
  },
  {
    id: "lesson-blockers",
    slug: "blockers-and-unblockers",
    title: "阻断牌和反阻断",
    category: "翻后策略",
    difficulty: "intermediate",
    content:
      "好的 bluff 候选通常阻断对手强价值牌，同时不阻断对手会弃掉的弱牌。好的 bluff-catch 也类似：阻断对手价值牌，不阻断对手错过听牌。",
    takeaways: ["阻断价值牌有利于 bluff。", "不阻断对手错过听牌有利于抓诈唬。", "阻断牌只是辅助，不替代范围判断。"],
  },
  {
    id: "lesson-mental-model",
    slug: "simple-study-loop",
    title: "个人练习循环",
    category: "学习方法",
    difficulty: "beginner",
    content:
      "单人训练最有效的方式是固定循环：先学概念，再做题，错题归类，然后复盘错因。每次只盯一个主题，比如 BTN vs BB c-bet，连续练到能解释原因再换主题。",
    takeaways: ["按主题练，不要随机乱刷。", "每题都说出范围理由。", "错题按概念归类。"],
  },
];

export const questions: Question[] = [
  {
    id: "q-btn-open-a9s",
    type: "preflop",
    category: "翻前范围",
    difficulty: "beginner",
    prompt: "6 人桌，前面都弃牌，你在 BTN 拿到 A9s。标准学习策略下更常见的行动是什么？",
    options: ["弃牌", "平跟", "开池加注", "全下"],
    answer: "开池加注",
    explanation: "BTN 位置优势最大，A9s 有高牌价值、同花潜力和阻断 A 的效果，通常属于可开池范围。",
    metadata: { heroPosition: "BTN", hand: "A9s" },
  },
  {
    id: "q-call-station-river",
    type: "exploit",
    category: "剥削策略",
    difficulty: "beginner",
    prompt: "对手是明显跟注站，河牌经常用边缘牌跟注。你拿到中等摊牌价值，错过听牌。更好的调整是什么？",
    options: ["增加纯诈唬", "减少纯诈唬，多做价值下注", "所有牌都过牌", "每次都超池下注"],
    answer: "减少纯诈唬，多做价值下注",
    explanation: "跟注站不会按理论频率弃牌，诈唬收益下降；但他们会用更差的牌支付价值下注。",
    metadata: { villainType: "calling-station" },
  },
  {
    id: "q-mdf-pot-half",
    type: "concept",
    category: "GTO 防守",
    difficulty: "intermediate",
    prompt: "底池 100，对手下注 50。只看 MDF 框架，你大约需要继续防守多少频率？",
    options: ["33%", "50%", "67%", "80%"],
    answer: "67%",
    explanation: "MDF = pot / (pot + bet) = 100 / 150 = 66.7%。实际选择哪些牌继续，要结合范围和牌面。",
    metadata: {},
  },
  {
    id: "q-cbet-dry-board",
    type: "concept",
    category: "翻后策略",
    difficulty: "intermediate",
    prompt: "BTN 开池，BB 跟注。翻牌 A72 彩虹面，BB 过牌。作为 BTN，理论学习中这个牌面对谁更有利？",
    options: ["BTN 更有利", "BB 更有利", "完全一样", "只看单手牌决定"],
    answer: "BTN 更有利",
    explanation: "BTN 翻前范围有更多强 A 和高张优势，A72r 也较干燥，常见策略会包含较高频率小注 c-bet。",
    metadata: { heroPosition: "BTN", board: "A72r", potType: "single-raised-pot" },
  },
  {
    id: "q-utg-k9o",
    type: "preflop",
    category: "翻前范围",
    difficulty: "beginner",
    prompt: "6 人桌，你在 UTG 拿到 K9o。没人行动前，标准学习策略更倾向怎么做？",
    options: ["开池加注", "弃牌", "平跟", "最小 3-bet"],
    answer: "弃牌",
    explanation: "UTG 后面还有 5 个玩家未行动，需要更紧的开池范围。K9o 被主导风险高，翻后可玩性也一般。",
    metadata: { heroPosition: "UTG", hand: "K9o" },
  },
  {
    id: "q-bb-defend-76s",
    type: "preflop",
    category: "盲注防守",
    difficulty: "intermediate",
    prompt: "BTN 开池到 2.5bb，你在 BB 拿到 76s。没有特殊对手信息时，更常见的学习思路是什么？",
    options: ["通常可以防守", "必须弃牌", "只应该全下", "永远 3-bet"],
    answer: "通常可以防守",
    explanation: "BB 已投入大盲，面对 BTN 宽范围开池， suited connector 有可玩性和隐含价值，常见策略会包含跟注防守。",
    metadata: { heroPosition: "BB", hand: "76s" },
  },
  {
    id: "q-small-cbet-purpose",
    type: "concept",
    category: "下注尺度",
    difficulty: "intermediate",
    prompt: "在 A72r 这类干燥且翻前进攻者有范围优势的牌面，小注 c-bet 的主要逻辑是什么？",
    options: ["用整个范围低成本施压", "只代表暗三条", "因为小注永远不会被加注", "为了保护所有空气牌到摊牌"],
    answer: "用整个范围低成本施压",
    explanation: "范围优势明显、牌面干燥时，小注能让很多边缘牌和空气牌获得即时 fold equity，同时保持风险可控。",
    metadata: { board: "A72r", potType: "single-raised-pot" },
  },
  {
    id: "q-wet-board-cbet",
    type: "concept",
    category: "牌面纹理",
    difficulty: "intermediate",
    prompt: "BTN 开池，BB 跟注。翻牌 987 两同花，BB 过牌。相比 A72r，BTN 应该如何调整？",
    options: ["更谨慎，降低自动 c-bet", "任何两张牌都下注", "只用 1bb 下注", "永远全下"],
    answer: "更谨慎，降低自动 c-bet",
    explanation: "987 两同花更连接 BB 防守范围，BB 有更多两对、顺子、强听牌。BTN 自动高频小注会更容易被反击。",
    metadata: { heroPosition: "BTN", board: "9h8h7c", potType: "single-raised-pot" },
  },
  {
    id: "q-overfold-exploit",
    type: "exploit",
    category: "剥削策略",
    difficulty: "beginner",
    prompt: "你观察到对手面对转牌第二枪弃牌明显过多。最直接的剥削调整是什么？",
    options: ["减少转牌 bluff", "增加转牌 bluff 和半诈唬", "只用坚果下注", "翻前不再开池"],
    answer: "增加转牌 bluff 和半诈唬",
    explanation: "对手过度弃牌时，你的 bluff 需要的成功率更容易达成，可以扩大施压频率，尤其选择有 equity 或好阻断的牌。",
    metadata: { villainType: "over-folder" },
  },
  {
    id: "q-underbluff-river",
    type: "exploit",
    category: "剥削策略",
    difficulty: "intermediate",
    prompt: "一个非常被动的玩家河牌突然大注。长期观察他几乎不 bluff。你拿到普通 bluff-catcher，应该如何调整？",
    options: ["按 MDF 强行跟注", "倾向弃牌", "必然加注 bluff", "忽略对手信息"],
    answer: "倾向弃牌",
    explanation: "MDF 假设对手有足够 bluff。若对手严重 bluff 不足，普通抓诈牌的 EV 会下降，剥削上可以过度弃牌。",
    metadata: { villainType: "passive-underbluffer" },
  },
  {
    id: "q-blocker-bluff",
    type: "concept",
    category: "阻断牌",
    difficulty: "intermediate",
    prompt: "河牌同花完成，你想选择 bluff 候选。哪类牌通常更适合？",
    options: ["持有高张同花阻断牌", "阻断对手所有错过听牌", "完全随机选", "只选最弱无阻断牌"],
    answer: "持有高张同花阻断牌",
    explanation: "高张同花阻断牌减少对手持有强同花的组合，使你的大注 bluff 更容易成功。但仍要结合范围和对手弃牌能力。",
    metadata: { board: "flush-complete" },
  },
  {
    id: "q-thin-value",
    type: "exploit",
    category: "价值下注",
    difficulty: "intermediate",
    prompt: "对手经常用第三对、A 高跟到河牌。你拿到顶对弱踢脚，河牌没有明显听牌完成。剥削上更常见的调整是？",
    options: ["考虑薄价值下注", "所有顶对都过牌", "把顶对转成 bluff", "只下注坚果"],
    answer: "考虑薄价值下注",
    explanation: "对手跟注过宽时，很多原本边缘的牌可以变成价值下注。关键是判断更差牌是否会支付。",
    metadata: { villainType: "loose-caller" },
  },
  {
    id: "q-pot-odds",
    type: "concept",
    category: "数学基础",
    difficulty: "beginner",
    prompt: "底池 100，对手下注 100。你跟注 100 后总底池 300。你大约需要多少胜率才能跟注不亏？",
    options: ["25%", "33%", "50%", "67%"],
    answer: "33%",
    explanation: "需要胜率 = 跟注金额 / 跟注后总底池 = 100 / 300 = 33.3%。",
    metadata: {},
  },
  {
    id: "q-polarized-bet",
    type: "concept",
    category: "下注结构",
    difficulty: "intermediate",
    prompt: "河牌使用大注时，理论上你的下注范围通常更应该是什么结构？",
    options: ["强价值牌 + 合适 bluff", "全部中等牌", "只有空气牌", "任何对子都下注"],
    answer: "强价值牌 + 合适 bluff",
    explanation: "大注给对手更差价格，通常需要两极化：强价值牌能被较强跟注范围支付，bluff 靠弃牌收益盈利。",
    metadata: {},
  },
];
